apiVersion: 1
datasources:
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    uid: influx_datasource_uid
    url: $INFLUX_URI
#    database: $INFLUX_DB
    database: $INFLUX_BUCKET
    isDefault: true
    jsonData:
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
#      password: $INFLUX_PASSWORD
      httpHeaderValue1: 'Token $INFLUX_TOKEN'
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: $INFLUX_URI
    secureJsonData:
      token: $INFLUX_TOKEN
    jsonData:
      version: Flux
      organization: $INFLUX_ORG
      defaultBucket: $INFLUX_BUCKET
      tlsSkipVerify: true

