apiVersion: 1
datasources:
  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    uid: influx_datasource_uid
    url: $INFLUX_URI
    database: $INFLUX_DB
    isDefault: true
    jsonData:
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token $INFLUX_TOKEN'